# This is a manual workflow to trigger the replacement of a resource
name: Terraform Replace

on:
  workflow_dispatch:
    inputs:
      resource_name:
        description: 'Resource Name'
        required: true

jobs:
  Restore:
    runs-on: ubuntu-latest
    steps:
    - name: Restore Resource
      run: terraform apply -replace="${{ github.event.inputs.resource_name}}"

    

